data_path : D:/stefan/GDB_Data/osm2_2014

model_year: 2018

main_log_file : 'run_log'

max_zone_number: 4000

node_offset: 0

max_regular_zone: 3700

update_network_from_projects : False

time_periods: ['AM', 'MD', 'PM', 'EV', 'NI']

reversibles:
  'AM' : [False, False]
  'MD' : [True, False]
  'PM' : [False, True]
  'EV' : [False, True]
  'NI' : [False, True]

extra_attributes:
  'LINK' : ['FacilityTy', 'CountyID', 'CountID']

# Directional attributes used for project updates & network thinning.
dir_columns: ['IJLanesGPAM', 'IJLanesGPMD', 'IJLanesGPPM', 'IJLanesGPEV', 'IJLanesGPNI', 'JILanesGPAM', 
'JILanesGPMD', 'JILanesGPPM', 'JILanesGPEV', 'JILanesGPNI', 'IJlanesGPadjust', 'JIlanesGPadjust', 
'IJLanesHOVAM', 'IJLanesHOVMD', 'IJLanesHOVPM', 'IJLanesHOVEV', 'IJLanesHOVNI', 'JILanesHOVAM', 
'JILanesHOVMD', 'JILanesHOVPM', 'JILanesHOVEV', 'JILanesHOVNI', 'IJSpeedLimit', 'JISpeedLimit', 
'IJVDFunc', 'JIVDFunc', 'IJLaneCapGP', 'IJLaneCapHOV', 'JILaneCapGP', 'JILaneCapHOV', 'IJSideWalks', 
'JISideWalks', 'IJBikeLanes', 'JIBikeLanes', 'IJLanesTR', 'JILanesTR', 'IJLanesTK', 'JILanesTK']

# Non-Directional attributes used for networkt thnning.
non_dir_columns : ['FacilityTy', 'NewFacilit', 'LinkType', 'projRteID', 'Modes', 'Oneway', 'CountID', 'CountyID', 'Processing_x']

# Attributes in addition to the dir_attributes that can get updated by projects
project_update_columns : ['projRteID', 'Change_Typ', 'Modes', 'FacilityTy']

intermediate_keep_columns : ['PSRCEdgeID', 'FacilityTy', 'NewFacilit', 'LinkType', 'Modes', 'INode', 'JNode', 'Oneway', 'CountID', 'CountyID', 'geometry', 'projRteID', 'Processing_x']

emme_link_columns : ['direction', 'i', 'j', 'length', 'modes', 'type', 'lanes', 'vdf', 'ul1', 'ul2', 'ul3']

additional_keep_columns: ['geometry', 'PSRCEdgeID', 'FacilityTy', 'Processing_x', 'projRteID', 'CountID', 'CountyID']

emme_node_columns : ['is_zone', 'i', 'Processing', 'P_RStalls', 'PSRCjunctI']

# links with these modes use time, not speed limit. 
link_time_modes : ['f', 'rc']

walk_links:
  direction: 1
  i: NewINode
  j: NewJNode
  modes: 'wk'
  type: 90
  lanes: 1
  vdf: 9
  ul1: 0
  ul2: 3
  ul3: 0

weave_links:
  direction: 1
  i: NewINode
  j: NewJNode
  modes: 'asehdimjgvutbpwl'
  length : 0.01
  type: 90
  lanes: 1
  vdf: 10
  ul1: 2000
  ul2: 0
  ul3: 0

standard_links:
  direction: 1
  i: NewINode
  j: NewJNode
  modes: Modes
  type: LinkType
  lanes: IJLanesGP
  vdf: IJVDFunc
  ul1: IJLaneCapGP
  ul2: IJSpeedLimit
  ul3: NewFacilit

hov_capacity: 'IJLaneCapHOV'

hov_lanes:
  1: 1
  2: 1
  3: 1
  4: 1
  5: 1
  7: 2
  12: 2
  14: 1

hov_modes:
  1: 'ahijbdmgp'
  2: 'aijbmgp'
  3: 'abp'
  4: 'abp'
  5: 'ashijbedmgp'
  7: 'ahijbdmgp'
  12: 'ashijbedmgp'
  14: 'ashijvbedmgp'

reverse_walk_link_facility_types : [4]
standard_facility_types : [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Projects are buffered before performing spatial join on edges to help select
# Edges that may not be perfectly covered by project routes. Adjusting this could 
# reduce errors reported in log file. 
project_buffer_dist : 1

# How far to shift HOV lanes from gP lanes:
hov_shift_dist : 1.906090351

build_turns: False    
build_transit: False

save_network_files : True  
create_emme_network: True
export_build_files: True
emme_folder_name: EMME
emmebank_title : networks
modes_file: modes.txt
transit_vehicle_file: vehicles.txt