edges:
  id: PSRCEdgeID
  project_id: projRteID
  project_start_year: InServiceDate
  i_node: NewINode
  j_node: NewJNode
  active_link_flag: ActiveLink
  id: PSRCEdgeID
  facility_type: FacilityType

junctions: 
  id: PSRCjunctID
  type: JunctionType
  node: EMME2nodeID

turns:
  id: TurnID
  junction: PSRCJunctID
  from_link_id: FrEdgeID
  to_link_id: ToEdgeID

transit_points:
  id: PSRCJunctID

model_links:
  facility_type: 'FacilityType'